In [1]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv(
    "bank_analytics_clean.csv"
)

In [3]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,age_group,balance_category,campaign_intensity
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no,46-60,Medium Balance,1 Contact
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no,36-45,Low Balance,1 Contact
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,26-35,Low Balance,1 Contact
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no,46-60,Medium Balance,1 Contact
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no,26-35,Low Balance,1 Contact

In [5]:
engine = create_engine(
    "mysql+pymysql://root:arbaz%40123@localhost/insightbank"
)

In [6]:
connection = engine.connect()

print("Database connected successfully")

Database connected successfully

In [7]:
df.to_sql(
    name="bank_campaign_data",
    con=engine,
    if_exists="replace",
    index=False
)

45211

In [8]:
query = """

SELECT

    COUNT(*) AS total_customers,

    SUM(
        CASE
            WHEN y = 'yes'
            THEN 1
            ELSE 0
        END
    ) AS successful_conversions,

    ROUND(
        SUM(
            CASE
                WHEN y = 'yes'
                THEN 1
                ELSE 0
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS conversion_rate

FROM bank_campaign_data;

"""

In [9]:
kpi_results = pd.read_sql(
    query,
    con=engine
)

kpi_results

   total_customers  successful_conversions  conversion_rate
0            45211                  5289.0             11.7